### ISSUE TITLE
Trying to build this project to get the DLL

### ISSUE THREAD

**Issue by reserect** [Kharzette/ClanWars#2]
Hi Sorry if this is not fixable but there was over 50 errors when me and my friend tried to build this for the DLL.
Could you possibly try it yourself to see if this is the case.

**Comment by Kharzette** [comment]
Yikes, I barely remember writing this.  I think the empyrion modding stuff has been greatly reworked since then.  I think I might have dabbled in something a year or so after this, maybe LCD Screens?

Anyway I'll see if I can find the bits I'm missing, which looks like a modding sample, and I'll see what happens.

**Comment by reserect** [comment]
Okay ty for getting in touch my friend says he just needs the project files as he managed to get rid of about 50 errors or something.

**Comment by Kharzette** [comment]
I'm not set up to build dotnet 4 anymore but with targetframework set to net6.0 it builds fine.

I had to update the submodule that points at an empyrion sample to the A11. 

I doubt it will work built with .net 6 though.  What sort of project files is he looking for?  Are you using vs code or visual studio?

**Comment by reserect** [comment]
We are still trying to figure it out is it possible to send the dll my way at all.

**Comment by Kharzette** [comment]
I did a release with the dll I built.  Give it a try, but I might be required to have the same dotnet version as Empyrion.  Let me know if it works and what the log files say if it doesn't.

**Comment by reserect** [comment]
Will have a go with it tomorrow to see how it goes i say tomorrow but i mean later as it's nearly 5am here lol. Thank you so much will def give it a try.

**Comment by reserect** [comment]
Does it have to be ran on a fresh game or can it be added mid play?

**Comment by reserect** [comment]
![image](https://user-images.githubusercontent.com/30455052/152655986-7357ab3e-80cc-49d9-8ba5-bb6ee388592d.png)

**Comment by reserect** [comment]
06-00:32:02.496 00_32 -LOG- {:EmpyrionModClient} ModDispatcher: ..\MODs\ClanWarsModule\ClanWarsModule.dll -> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at EmpyrionModHost.ModDispatcher.LoadAssembly(String aFileName)
06-00:32:02.496 00_32 -LOG- {:EmpyrionModClient} ModDispatcher: ..\MODs\ClanWarsModule\ClanWarsModule.dll -> LE:System.IO.FileNotFoundException: Could not load file or assembly 'System.ComponentModel.TypeConverter, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.ComponentModel.TypeConverter, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Assembly not found
File name: 'G:\Empyrion - Dedicated Server\DedicatedServer\EmpyrionDedicated_Data\Managed\System.ComponentModel.TypeConverter.dll'
   at EmpyrionModHost.ModDispatcher.ModResolveEventHandler(Object aSender, ResolveEventArgs aArgs)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)

**Comment by Kharzette** [comment]
Ok I THINK that means that you don't have the dotnet 6 runtime installed.  If there is such a thing.

Try installing dotnet6 and see if that works.  I have my doubts though.

Did you ever get any closer to building with whatever version empyrion is using?  I don't have any of that stuff installed anymore.

**Comment by reserect** [comment]
Hi again so installed Dotnet 6.0 Runtime and still pushing the same error. I will try and do some more digging and let you know.

Will try and do it with the up to date version

**Comment by reserect** [comment]
06-17:57:47.385 17_57 -LOG- {:EmpyrionModClient} Exception [ClanWarsModule.ClanWars] Game_Start => System.IO.FileNotFoundException: Could not find file 'G:\Empyrion - Dedicated Server\Content\Mods\ModLoader\MODs\ClanWarsModule\ItemPointValues.txt'.
File name: 'G:\Empyrion - Dedicated Server\Content\Mods\ModLoader\MODs\ClanWarsModule\ItemPointValues.txt'
   at System.IO.Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at ClanWarsModule.AIQueen.LoadPointValues()
   at ClanWarsModule.AIQueen..ctor(Single nearDist)
   at ClanWarsModule.ClanWars.Game_Start(ModGameAPI dediAPI)
   at EmpyrionModHost.ModDispatcher.<>cDisplayClass30_0.<Game_Start>b3()
   at EmpyrionModHost.ModDispatcher.<>cDisplayClass35_0.<SafeApiCall>g__SafeCall|0()
   
   We have managed to get this far with it.

**Comment by Kharzette** [comment]
Oh yea, these data files need to be copied in alongside the DLL

Constants.txt
ItemPointValues.txt

**Comment by reserect** [comment]
Thanks for replying back i did that already i think it's more of a security permissions issue but it still is not budging no matter what perm i throw at it.

**Comment by Kharzette** [comment]
Hmm if it is file not found... I'm having a strange memory like maybe the txt files need to be one directory up?  Lemme look at the code

**Comment by Kharzette** [comment]
Hmm no it does find the dll's directory, so it should be alongside the dll.  I dunno what would make it not find it

**Comment by reserect** [comment]
I'll try a few more ideas tomorrow if anything hopefully i get somewhere. it's something to do wuith windows security perms
FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath,

also will try another way to load it in was using modloader to load it into empyrion will maybe try the other aproach.

**Comment by reserect** [comment]
Okay so we managed to get it to create and work but now i am having a issue with it spamming the server chat with Tyada now lol 
![image](https://user-images.githubusercontent.com/30455052/153099091-248e1122-d58b-496f-9ce6-4202c850a302.png)

**Comment by reserect** [comment]
![image](https://user-images.githubusercontent.com/30455052/153108620-e3027696-89ba-4b1e-9db8-f415f164e16e.png)
managed to get it to just show this. stopped the spam

**Comment by Kharzette** [comment]
Sorry I lost power and all my tabs and forgot about this!  I think the config file is set up for teams of 8v8?  You should edit constants.txt with the team size you want.  You can also change the match duration.

**Comment by Kharzette** [comment]
You are using this with the workshop scenario right?

**Comment by reserect** [comment]
I think the mod needs updating too :(

**Comment by reserect** [comment]
Mono path[0] = 'L:/SteamLibrary/steamapps/common/Empyrion - Galactic Survival/DedicatedServer/EmpyrionDedicated_Data/Managed'
Mono config path = 'L:/SteamLibrary/steamapps/common/Empyrion - Galactic Survival/DedicatedServer/MonoBleedingEdge/etc'
Initialize engine version: 2021.1.17f1 (03b40fe07a36)
[Subsystems] Discovering subsystems at path L:/SteamLibrary/steamapps/common/Empyrion - Galactic Survival/DedicatedServer/EmpyrionDedicated_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1; jobified=0
Direct3D:
    Version:  Direct3D 11.0 [level 11.1]
    Renderer: Radeon RX 590 Series (ID=0x67df)
    Vendor:   ATI
    VRAM:     8171 MB
    Driver:   30.0.13023.4001
Begin MonoManager ReloadAssembly
- Completed reload, in  0.138 seconds
D3D11 device created for Microsoft Media Foundation video decoding.
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

UnloadTime: 0.524600 ms
11-14:12:59.657 14_12 -LOG- Args: L:\SteamLibrary\steamapps\common\Empyrion - Galactic Survival\Client/../DedicatedServer/EmpyrionDedicated.exe -logFile ../Logs/3649/Dedicated_220211-141256-97.log -dedicated L:\SteamLibrary\steamapps\common\Empyrion - Galactic Survival\Client/../Saves/Games/reserectsnewtest/dedicated.yaml -gamename reserectsnewtest -localdedi
11-14:12:59.684 14_12 -LOG- Dedi log path = L:\SteamLibrary\steamapps\common\Empyrion - Galactic Survival\DedicatedServer\EmpyrionDedicated_Data\..\..\Logs\3649
11-14:12:59.722 14_12 -LOG- *************************************************************************
11-14:12:59.722 14_12 -LOG- Dedicated Server Empyrion - Galactic Survival
11-14:12:59.722 14_12 -LOG- Version: v1.7.3
11-14:12:59.723 14_12 -LOG- Build: 3649
11-14:12:59.723 14_12 -LOG- Platform: Win, 64 Bit
11-14:12:59.723 14_12 -LOG- OS: Windows 10  (10.0.19044) 64bit
11-14:12:59.723 14_12 -LOG- DRAM: 98218
11-14:12:59.723 14_12 -LOG- CPU: AMD Ryzen 7 3800X 8-Core Processor 
11-14:12:59.723 14_12 -LOG- Freq: 4500
11-14:12:59.723 14_12 -LOG- Cores: 16
11-14:12:59.723 14_12 -LOG- Gfx: Radeon RX 590 Series
11-14:12:59.724 14_12 -LOG- VRAM: 8171
11-14:12:59.725 14_12 -LOG- SL: 5
11-14:12:59.725 14_12 -LOG- Force DX9: False
11-14:12:59.725 14_12 -LOG- Instancing: False
11-14:12:59.726 14_12 -LOG- TimeZone: +00:00
11-14:12:59.726 14_12 -LOG- Culture: en-GB
11-14:12:59.727 14_12 -LOG- Last build: 3649
11-14:12:59.727 14_12 -LOG- Dedicated server build
11-14:12:59.729 14_12 -LOG- Build: Release (variableCollection)
11-14:12:59.729 14_12 -LOG- MainThreadId: 15956
11-14:12:59.729 14_12 -LOG- *************************************************************************
11-14:12:59.729 14_12 -LOG- Limiting the number of worker threads on a dedicated server to 8
11-14:12:59.911 14_12 -LOG- Loading file 'L:\SteamLibrary\steamapps\common\Empyrion - Galactic Survival\Client/../Saves/Games/reserectsnewtest/dedicated.yaml'
11-14:12:59.975 14_12 -LOG- Using game name 'reserectsnewtest' from command line
11-14:13:00.732 14_13 -LOG- Started a new game
11-14:13:01.520 14_13 -LOG- Game dat not found, creating new one
11-14:13:01.560 14_13 -EXC- YamlDotNet.Core.YamlException: (Line: 3, Col: 3, Idx: 26) - (Line: 3, Col: 3, Idx: 26): Exception during deserialization ---> System.Runtime.Serialization.SerializationException: Property 'SectorPlanets' not found on type 'Assembly-CSharp.ActionType'.
  at YamlDotNet.Serialization.TypeInspectors.TypeInspectorSkeleton.GetProperty (System.Type type, System.Object container, System.String name, System.Boolean ignoreUnmatched) [0x0005c] in <b6723ca1a1d1438d86c7787c4ef6ea38>:0 
  at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize (YamlDotNet.Core.IParser parser, System.Type expectedType, System.Func`3[T1,T2,TResult] nestedObjectDeserializer, System.Object& value) [0x0003e] in <b6723ca1a1d1438d86c7787c4ef6ea38>:0 
  at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue (YamlDotNet.Core.IParser parser, System.Type expectedType, YamlDotNet.Serialization.Utilities.SerializerState state, YamlDotNet.Serialization.IValueDeserializer nestedObjectDeserializer) [0x00039] in <b6723ca1a1d1438d86c7787c4ef6ea38>:0 
   --- End of inner exception stack trace ---
  at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue (YamlDotNet.Core.IParser parser, System.Type expectedType, YamlDotNet.Serialization.Utilities.SerializerState state, YamlDotNet.Serialization.IValueDeserializer nestedObjectDeserializer) [0x0009e] in <b6723ca1a1d1438d86c7787c4ef6ea38>:0 
  at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue (YamlDotNet.Core.IParser parser, System.Type expectedType, YamlDotNet.Serialization.Utilities.SerializerState state, YamlDotNet.Serialization.IValueDeserializer nestedObjectDeserializer) [0x0006e] in <b6723ca1a1d1438d86c7787c4ef6ea38>:0 
  at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer+<>c__DisplayClass3_0.<DeserializeValue>b__0 (YamlDotNet.Core.IParser r, System.Type t) [0x00000] in <b6723ca1a1d1438d86c7787c4ef6ea38>:0 
  at YamlDotNet.Serialization.NodeDeserializers.ObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize (YamlDotNet.Core.IParser parser, System.Type expectedType, System.Func`3[T1,T2,TResult] nestedObjectDeserializer, System.Object& value) [0x0006b] in <b6723ca1a1d1438d86c7787c4ef6ea38>:0 
  at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue (YamlDotNet.Core.IParser parser, System.Type expectedType, YamlDotNet.Serialization.Utilities.SerializerState state, YamlDotNet.Serialization.IValueDeserializer nestedObjectDeserializer) [0x00082] in <b6723ca1a1d1438d86c7787c4ef6ea38>:0 
  at YamlDotNet.Serialization.ValueDeserializers.AliasValueDeserializer.DeserializeValue (YamlDotNet.Core.IParser parser, System.Type expectedType, YamlDotNet.Serialization.Utilities.SerializerState state, YamlDotNet.Serialization.IValueDeserializer nestedObjectDeserializer) [0x0006e] in <b6723ca1a1d1438d86c7787c4ef6ea38>:0 
  at YamlDotNet.Serialization.Deserializer.Deserialize (YamlDotNet.Core.IParser parser, System.Type type) [0x0004e] in <b6723ca1a1d1438d86c7787c4ef6ea38>:0 
  at YamlDotNet.Serialization.Deserializer.Deserialize (System.IO.TextReader input, System.Type type) [0x00007] in <b6723ca1a1d1438d86c7787c4ef6ea38>:0 
  at YamlDotNet.Serialization.Deserializer.Deserialize[T] (System.IO.TextReader input) [0x00000] in <b6723ca1a1d1438d86c7787c4ef6ea38>:0 
  at Assembly-CSharp.PartitionEditor.DisconnectSymbol[A] (System.IO.TextReader , System.String , System.Boolean , System.Boolean ) [0x0000f] in <8847d4e7a3c249f382fd0e085adac37b>:0 
NullReferenceException: Object reference not set to an instance of an object
  at Assembly-CSharp.FunctionTable.IncreaseFile (System.String , System.Boolean ) [0x000cf] in <8847d4e7a3c249f382fd0e085adac37b>:0 
  at Assembly-CSharp.FunctionTable.DisconnectSymbol (System.Boolean , System.Int32 , System.String , Assembly-CSharp.ProjectService+SymbolStack ) [0x00053] in <8847d4e7a3c249f382fd0e085adac37b>:0 
  at Assembly-CSharp.WindowLayout.DetachPartition () [0x004fd] in <8847d4e7a3c249f382fd0e085adac37b>:0 
  at MBS_S.set_ExitDockingPane (MBS_S+ReferenceSite ) [0x00014] in <8847d4e7a3c249f382fd0e085adac37b>:0 
  at GameStartup.Awake () [0x002af] in <8847d4e7a3c249f382fd0e085adac37b>:0

**Comment by reserect** [comment]
![image](https://user-images.githubusercontent.com/30455052/153631609-2cd92624-26ed-4920-ac0b-e12136a751c7.png)
Managed to merge it with Reforged Eden added the planets to the configs and such and went from there :)

**Comment by reserect** [comment]
Also stopped the spamming in the server chat and the top of the screen does not constantly appear when on planets other than Tyada and Castae. so all is good up to now :)

**Comment by Kharzette** [comment]
Awesome you made it to the start points!  Did it unlock the doors?  I think it balances the teams then unlocks the doors or something.

**Comment by reserect** [comment]
The doors are coded so had to go to each one and manually add a code this will make a good pvp server but also a competition one events and such :)

**Comment by reserect** [comment]
okay so if 8 players are in that one space the doors unlock if so that is pretty cool. I know the snippets i added to the reforged works as it told me i sacrificed myself to the queen and lost stuff lol

**Comment by reserect** [comment]
i have a server up at the minute and with reforged it adds 15 starter planets so with tyada and castae it makes 17 starter planets so easy to have it as a decide what you wanna do kinda server. tyada and castae as event platform and the rest for leveling and such with out disturbing others :)

**Comment by Kharzette** [comment]
Very cool, yea you can change the team size and such.  I forget what happens at the end of the "match"
